Connect Achievement Popup at Endgame Scene to API
KlongdinsorLab/PlakodGames pull request #66
Opened 2024-08-29 07:58 UTC by EgapNimda

2024-08-31 04:04 UTC, StampChanathip requested changes

2024-08-31 04:04 UTC, StampChanathip commented on space_invader/src/scene/EndGameScene.ts
> +			achievementIdList.push(achievement.id)
น่าจะเขียนแบบนี้ได้เลยมั้ยนะ
`const achievementIdList = achievementList.map((achievement) => achievment.id)`

2024-08-31 04:04 UTC, StampChanathip commented on space_invader/src/scene/EndGameScene.ts
> +		const achievementList : any[] = response.new_achievements
เห็นแล้วเพิ่งนึกได้ พี่ว่าเราไปสร้างไฟล์ใน services/API/backend ชื่อ apiResponseType.ts ก็ได้ครับ เอาไว้ define type ของ response ที่ได้จาก backend กันไว้ดีกว่า 

เวลารับ response มาแล้วเอาไปใช้จะได้ typesafe และไม่ต้องใช้ any

2024-08-31 04:04 UTC, StampChanathip commented on space_invader/src/services/API/backend/supabaseAPIService.ts
> +	async finishGameSession({ score, lap, is_booster_received }: { score: number; lap: number, is_booster_received: boolean }) {
ฝาก define type ของ response แล้วใส่เพิ่มใน return type ของ function นี้หน่อยครับ

2024-08-31 06:31 UTC, EgapNimda commented on space_invader/src/scene/EndGameScene.ts
> +		const achievementList : any[] = response.new_achievements
จริง ๆ มันมีที่พีซทำไว้แล้วครับ อยู่ใน service/API/definition/responseDTO.d.ts ครับ แต่มันไม่ตรง ถ้าจะใช้ เดี๋ยวไปไล่แก้ทีละอันละกันครับ

เดี๋ยวผมแก้ Achievement เสร็จแล้วจะ Push ขึ้นไปครับ

2024-09-01 03:11 UTC, StampChanathip approved these changes

2024-09-01 03:12 UTC, merged